FROM php:8.2-fpm-alpine

# Install tools dasar dan extension PostgreSQL
RUN apk add --no-cache nginx supervisor curl libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Atur folder kerja
WORKDIR /var/www/html
COPY . .

# Ambil composer terbaru dan install dependencies
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install --no-dev --optimize-autoloader --no-scripts

# PENTING: Paksa buka izin folder storage & bootstrap agar tidak Error 500 karena permission
RUN mkdir -p /var/www/html/storage/framework/cache/data \
    && mkdir -p /var/www/html/storage/framework/sessions \
    && mkdir -p /var/www/html/storage/framework/views \
    && chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 8080

# PAKSA BYPASS: Hapus file cache sebelum server dinyalakan
CMD php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}