FROM php:8.2-fpm-alpine

# Jalankan instalasi tools dasar dan extension PostgreSQL yang stabil
RUN apk add --no-cache nginx supervisor curl libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Atur folder kerja
WORKDIR /var/www/html
COPY . .

# Ambil composer terbaru
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Jalankan install tanpa scripts dulu biar gak crash karena cache env
RUN composer install --no-dev --optimize-autoloader --no-scripts

# Atur permission folder storage wajib Laravel
RUN chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache

# Buka port untuk Railway
EXPOSE 8080

# Jalankan server lewat baris perintah php artisan biasa
CMD php artisan config:clear && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}